-- Jobwork module (Minis → Jobwork), part 2: tables.
--
-- WHY: work sourced outside the company (embroidery, dyeing, printing,
-- handwork, stitching…) was tracked nowhere. Material goes OUT to a
-- jobworker and finished pieces come back IN, in parts, over weeks — a
-- purchase order only models goods coming in, which is why the PO module's
-- 'job_work' type has never been used. The owner wants: how much was given,
-- how much came back and when, what is still with the jobworker, the agreed
-- price, and whether it has been paid.
--
-- Shape:
--   jobwork_orders        one job: jobworker × job type × SKU, pieces, rate/pc
--   jobwork_materials     what the job consumes (name, unit, optional usage/pc)
--   jobwork_entries       one dated movement: OUT (material sent, rework pcs
--                         sent back) or IN (pcs OK / rejected, material returned)
--   jobwork_entry_lines   material quantities on an entry
--   jobwork_payments      money paid against a job
--   jobwork_order_summary per-job totals (pcs, bill, paid, due) for the list
--
-- Jobworkers are po_vendors rows, the same master Purchase Orders uses, so a
-- vendor is never entered twice. Bill = pieces received OK × rate.
-- Roles: admin/manager/operator create jobs, send out and receive;
-- payments, cancel, reopen and deleting entries are admin/manager only.
-- Multi-row writes go through SECURITY INVOKER RPCs (RLS still applies)
-- that lock the job row, so two people receiving at once cannot over-count.

create table public.jobwork_orders (
  id uuid primary key default gen_random_uuid(),
  jw_number integer generated by default as identity unique,
  vendor_id uuid references public.po_vendors(id) on delete set null,
  vendor_name text not null check (btrim(vendor_name) <> ''),
  vendor_phone text,
  job_type text not null check (btrim(job_type) <> ''),
  sku text not null check (btrim(sku) <> ''),
  component text,
  costing_product_id uuid references public.costing_products(id) on delete set null,
  pieces integer not null check (pieces > 0),
  rate numeric not null default 0 check (rate >= 0),
  job_date date not null default public.jw_today(),
  expected_date date,
  status text not null default 'open' constraint chk_jobwork_status check (status in ('open', 'closed', 'cancelled')),
  notes text,
  close_reason text,
  closed_at timestamptz,
  closed_by uuid references public.profiles(id),
  created_by uuid references public.profiles(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index jobwork_orders_status_idx on public.jobwork_orders (status);
create index jobwork_orders_vendor_idx on public.jobwork_orders (vendor_id);
create index jobwork_orders_sku_idx on public.jobwork_orders (sku);
create index jobwork_orders_created_idx on public.jobwork_orders (created_at desc);

create table public.jobwork_materials (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.jobwork_orders(id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  unit text not null check (btrim(unit) <> ''),
  per_piece numeric check (per_piece is null or per_piece >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index jobwork_materials_order_idx on public.jobwork_materials (order_id);

create table public.jobwork_entries (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.jobwork_orders(id) on delete cascade,
  kind text not null constraint chk_jobwork_entry_kind check (kind in ('out', 'in')),
  entry_date date not null default public.jw_today(),
  pcs_ok integer not null default 0 check (pcs_ok >= 0),
  pcs_rejected integer not null default 0 check (pcs_rejected >= 0),
  pcs_rework integer not null default 0 check (pcs_rework >= 0),
  note text,
  created_by uuid references public.profiles(id) default auth.uid(),
  created_at timestamptz not null default now(),
  constraint chk_jobwork_entry_pcs check (
    (kind = 'out' and pcs_ok = 0 and pcs_rejected = 0) or (kind = 'in' and pcs_rework = 0))
);
create index jobwork_entries_order_idx on public.jobwork_entries (order_id, entry_date);

create table public.jobwork_entry_lines (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references public.jobwork_entries(id) on delete cascade,
  material_id uuid not null references public.jobwork_materials(id) on delete restrict,
  qty numeric not null check (qty > 0),
  created_at timestamptz not null default now()
);
create index jobwork_entry_lines_entry_idx on public.jobwork_entry_lines (entry_id);
create index jobwork_entry_lines_material_idx on public.jobwork_entry_lines (material_id);

create table public.jobwork_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.jobwork_orders(id) on delete restrict,
  pay_date date not null default public.jw_today(),
  amount numeric not null check (amount > 0),
  mode text not null default 'cash' constraint chk_jobwork_pay_mode check (mode in ('cash', 'bank', 'upi', 'cheque', 'other')),
  reference text,
  note text,
  created_by uuid references public.profiles(id) default auth.uid(),
  created_at timestamptz not null default now()
);
create index jobwork_payments_order_idx on public.jobwork_payments (order_id, pay_date);

-- RLS on in the same migration that creates the tables; policies follow in
-- jobwork_guards_rls (until then nobody can read or write — fail closed).
alter table public.jobwork_orders enable row level security;
alter table public.jobwork_materials enable row level security;
alter table public.jobwork_entries enable row level security;
alter table public.jobwork_entry_lines enable row level security;
alter table public.jobwork_payments enable row level security;
